### ISSUE TITLE
Ring

### ISSUE THREAD

**Issue by ayakomachi** [tanda/wedding#12]
- [x] Look for shops

- [x] Decide a shop

- [x] Select design

- [x] Buy the one

**Comment by domofactor** [comment]
here's a couple carbon ones I found:

https://www.etsy.com/listing/466660935/black-tungsten-wedding-band-black-carbon?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=carbon%20fiber%20ring&ref=sr_gallery-1-6

https://www.etsy.com/listing/517491848/two-tone-tungsten-wedding-band-black?ref=related-1
